apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-apache-server
spec:
  selector:
    matchLabels:
      app: sample-apache-server
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-apache-server
    spec:
      containers:
      - name: sample-apache-server
        image: shubheq/sample-ha
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sample-apache-server-service
spec:
  selector:
    app: sample-apache-server
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
